Add basic admin auth flow
Autistalive/web pull request #24
Opened 2024-01-28 03:32 UTC by maotovisk

1. Added `Admin` model.
2. Set up the admin guard in `config/auth.php`.
3. Duplicated and refactored the generated files to accommodate the new guard and `PasswordBroker`.
4. Added a Admin seeder.

2024-01-28 09:05 UTC, norththefirst requested changes
Add some feature tests please

2024-01-28 09:05 UTC, norththefirst commented on database/seeders/DatabaseSeeder.php
> +            'email' => 'test@test.com',
Emails are marked as unique, make sure to add a faker

2024-01-28 09:05 UTC, norththefirst commented on database/seeders/DatabaseSeeder.php
> +            'email' => 'test@test.com',
Make sure to add a faker to this one too

2024-01-28 20:09 UTC, norththefirst approved these changes

2024-01-29 12:12 UTC, clys-man approved these changes

2024-01-29 12:12 UTC, merged